posts/urls.py
"""Post Urls"""
#django
from django.urls import path

#posts
from . import views

urlpatterns = [
    path(
        route='', 
        view=views.PostsFeedView.as_view(), 
        name='feed'
    ),
    path(
        route='posts/new', 
        view=views.CreatePostView.as_view(), 
        name='create'
    ),
    path(
        route='post/<int:pk>/',
        view=views.PostDetailView.as_view(),
        name='detail'
    ),
]

travelgram/urls.py
#Django
from django.contrib import admin
from django.urls import path, include
# the next tow imports are by images Files
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #admin
    path('admin/', admin.site.urls),
    #posts
    path('', include(('posts.urls', 'posts'), namespace='posts')),

    #users
    path('users/', include(('users.urls', 'users'), namespace='users')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
"""Users urls"""
#django
from django.urls import path

#users
from . import views

urlpatterns = [

    # management
    path(
        route='login/', 
        view=views.LoginView.as_view(), 
        name='login'
    ),
    path(
        route='logout/', 
        view=views.LogoutView.as_view(), 
        name='logout'
    ),
    path(
        route='signup/', 
        view=views.SignupView.as_view(), 
        name='signup'
    ),
    path(
        route='me/profile',
        view=views.UpdateProfileView.as_view(), 
        name='update_profile'
    ),
    # post
    path(
        route='<str:username>/',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link
      rel="shortcut icon"
      href="{% static 'img/travelgram.png' %}"
      type="image/x-icon"
    />
  </head>
  <body>
    {% include "nav.html" %}
    <div class="container mt-5">
      {% block container %}
      {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top">
    <div class="container">
        <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url 'posts:feed' %}">
            <img src="{% static 'img/travelgram.png' %}" height="45" class="d-inline-block align-top">
        </a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a href="{% url 'users:detail' request.user.username %}">
                        {% if request.user.profile.picture %}
                            <img src="{{ request.user.profile.picture.url }}" height="35" width="35" class="d-inline-block align-top rounded-circle">
                        {% else %}
                            <img src="{% static 'img/default-profile.png' %}" height="35" width="35" class="d-inline-block align-top rounded-circle">
                        {% endif %}
                    </a>
                </li>
                <li class="nav-item nav-icon">
                    <a href="{% url 'posts:create' %}">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>
                <li class="nav-item nav-icon">
                    <a href="#" data-toggle="modal" data-target="#exampleModalCenter">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
	<h5 class="modal-title" id="exampleModalLongTitle">Logout Confirmation</h5>
	<button type="button" class="close" data-dismiss="modal" aria-label="Close">
	  <span aria-hidden="true">&times;</span>
	</button>
      </div>
      <div class="modal-body">
	Are you sure you want to logout?
      </div>
      <div class="modal-footer">
	<form action="{% url 'users:logout' %}" method="post">
	    {% csrf_token %}
	    <div class="text-center">
		<button type="submit" class="btn btn-primary mr-2">Logout</button>
            	<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
	    </div>
	</form>
      </div>
    </div>
  </div>
</div>

templates/pagination.html
<nav class="mt-3">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj_previous_page_number }}">
                    Previous
                </a>
            </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link" href="#">
                {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </a>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Next
            </a>
        </li>
        {% endif %}
    </ul>
</nav>