posts/urls.py
"""Post Urls"""
#django
from django.urls import path

#posts
from . import views

urlpatterns = [
    path(
        route='', 
        view=views.PostsFeedView.as_view(), 
        name='feed'
    ),
    path(
        route='posts/new', 
        view=views.CreatePostView.as_view(), 
        name='create'
    ),
    path(
        route='post/<int:pk>/',
        view=views.PostDetailView.as_view(),
        name='detail'
    ),
]

travelgram/urls.py
#Django
from django.contrib import admin
from django.urls import path, include
# the next tow imports are by images Files
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #admin
    path('admin/', admin.site.urls),
    #posts
    path('', include(('posts.urls', 'posts'), namespace='posts')),

    #users
    path('users/', include(('users.urls', 'users'), namespace='users')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
"""Users urls"""
#django
from django.urls import path

#users
from . import views

urlpatterns = [

    # management
    path(
        route='login/', 
        view=views.LoginView.as_view(), 
        name='login'
    ),
    path(
        route='logout/', 
        view=views.LogoutView.as_view(), 
        name='logout'
    ),
    path(
        route='signup/', 
        view=views.SignupView.as_view(), 
        name='signup'
    ),
    path(
        route='me/profile',
        view=views.UpdateProfileView.as_view(), 
        name='update_profile'
    ),
    # post
    path(
        route='<str:username>/',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
]

users/models.py
"""Users models."""
#Django
from django.contrib.auth.models import User
from django.db import models

class Profile(models.Model):
    """Profile model.

    Proxy model that extends the base data 
    with other information
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(max_length=200, blank=True)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)
    picture = models.ImageField(
        upload_to='users/pictures', 
        blank=True,
        null=True 
    )
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return username"""
        return self.user.username

users/forms.py
"""User Forms"""
#Django
from django import forms
from django.contrib.auth.models import User

#models
from .models import Profile
from .models import User

class SignupForm(forms.Form):
    """Signup form"""
    username = forms.CharField(
        min_length=4, 
        max_length=50,
        widget=forms.TextInput(attrs={
            'class':'form-control',
            'placeholder':'Username'
        })
    )
    password = forms.CharField(
        max_length=70, 
        widget=forms.PasswordInput(attrs={
            'class':'form-control',
            'placeholder':'password'
        })
    )
    password_confirmation = forms.CharField(
        max_length=70, 
        widget=forms.PasswordInput(attrs={
            'class':'form-control',
            'placeholder':'Confirm password'
        })
    )

    first_name = forms.CharField(
        min_length=2, 
        max_length=50,
        widget=forms.TextInput(attrs={
            'class':'form-control',
            'placeholder':'First Name'
        })
    )
    last_name = forms.CharField(
        min_length=2, 
        max_length=50,
        widget=forms.TextInput(attrs={
            'class':'form-control',
            'placeholder':'Last Name'
        })
    )

    email = forms.CharField(
        min_length=6, 
        max_length=70, 
        widget=forms.EmailInput(attrs={
            'class':'form-control',
            'placeholder':'Email'
        })
    )

    def clean_username(self):
        """Username must be unique"""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Username is already in use')
        return username

    def clean(self):
        """Verify password confirmation match"""
        data = super().clean()
        password = self.cleaned_data['password']
        password_confirmation = self.cleaned_data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Password do not match')
        return data
    
    def save(self):
        """Create user and profile"""
        data = self.cleaned_data
        data.pop('password_confirmation')

        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()

users/views.py
"""Users views"""
#django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from django.views.generic import DetailView, FormView, UpdateView
from django.urls import reverse, reverse_lazy
from django.contrib.auth.models import User

#users
from .forms import SignupForm
from .models import Profile

#posts
from posts.models import Post

class UserDetailView(LoginRequiredMixin, DetailView):
    template_name = 'users/detail.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    queryset = User.objects.all()
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        """Add user's posts to context"""
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['posts'] = Post.objects.filter(user=user).order_by('-created')

        return context

class SignupView(FormView):
    """Users signup view"""
    template_name = 'users/signup.html'
    redirect_authenticated_user = True
    form_class = SignupForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        """Save form data"""
        form.save()
        return super().form_valid(form)

class UpdateProfileView(LoginRequiredMixin, UpdateView):
    """Update profile view"""
    template_name = 'users/update_profile.html'
    model = Profile
    fields = ['website', 'biography', 'phone_number', 'picture']

    def get_object(self):
        """Return user's profile """
        return self.request.user.profile

    def get_success_url(self):
        """Return ti user's profile"""
        username = self.object.user.username
        return reverse('users:detail', kwargs = {'username': username})

class LoginView(auth_views.LoginView):
    """Login view"""
    template_name = 'users/login.html'
    redirect_authenticated_user = True

class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    """Logout view""" 
    next_page = reverse_lazy('users:login')

templates/users/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link
    rel="shortcut icon"
    href="{% static 'img/travelgram.png' %}"
    type="image/x-icon"
  />
  </head>
  <body class="h-100">
    <div class="container h-100">
      <div class="row h-100 justify-content-center align-items-center">
        <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">
          <img src="{% static 'img/travelgram.png' %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">
          {% block container %}{% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

templates/users/detail.html
{% extends "base.html" %}

{% block head_content %}
<title>@{{ user.username}} | Travelgram</title>
{% endblock %}

{% block container %}
<div class="container mb-5" style="margin-top: 8em;">
    <div class="row">
        <div class="col-sm-4 d-flex justify-content-center">
            <img src="{{ user.profile.picture.url }}" alt="@{{user.username}}" class="rounded-circle" width="150px">
        </div>
        <div class="col-sm-8">
            <h2 style="font-weight: 100;">
                {{user.username}}
                {% if user == request.user %}
                    <a href="{% url 'users:update_profile' %}"
                        class="ml-5 btn btn-sm btn-outline-info"
                    >
                        Edit profile
                    </a>
                {% else %}
                    <a href=""
                        class="ml-5 btn btn-sm btn-primary"
                    >
                        Follow
                    </a>
                {% endif %}
            </h2>
            <div class="row mt-2" style="font-size: 1.2em;">
                <div class="col-sm-4">
                    <b>{{users.profile.posts_count}}785</b> posts
                </div>
                <div class="col-sm-4">
                    <b>{{users.profile.followers}}401</b> followers
                </div>
                <div class="col-sm-4">
                    <b>{{users.profile.following}}491</b> following
                </div>
            </div>
            <div class="row mt-4">
                <div class="col-sm-12">
                    <p>{{user.profile.biography}}</p>
                </div>
            </div>
        </div>
    </div>
</div>

<hr>

<div class="container" id="user-posts">
    <div class="row mt-3">
        {% for post in posts %}
        <div class="col-sm-4 pt-5 pb-5 pr-5 pl-5 d-flex justify-content-center align-items-center">
            <a href="" class="border">
                <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid">
            </a>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock%}

templates/users/login.html
{% extends "users/base.html" %}

{% block head_content %}
<title>Travelgram sign in</title>
{% endblock %}

{% block container %}

{% if form.errors %}
<p class="alert alert-danger">
  Your username and password didn't match. Please try again.
</p>
{% endif %}

<form method="POST" action="{% url 'users:login' %}">
  {% csrf_token %}
    <div class="form-group">
      <input class="form-control mb-2" type="text" placeholder="Username" name="username" />
      <input class="form-control" type="password" placeholder="Password" name="password" />
    </div>
    <button class="btn btn-primary btn-block" type="submit">Sign in</button>
</form>
<p class="mt-4">Don't have an account yet? <a href="{% url 'users:signup' %}">sign up here.</a></p>

{% endblock %}

templates/users/signup.html
{% extends "users/base.html" %}

{% block head_content %}
<title>Travelgram sign up</title>
{% endblock %}

{% block container %}
<form action="{% url 'users:signup' %}" method="POST">
    {% csrf_token %}
    {% if form.non_field_errors %}
        <div class="alert alert-danger">
            {% for error in form.non_field_errors %}
                {{ error }}
            {% endfor %}
        </div>
    {% endif %}
    {% for field in form %}
        <div class="form-group">
            {{ field.label_tag }}
            {{ field }}
            {% if field.errors %}
                {% for error in field.errors %}
                    <p class="alert alert-danger">{{ error }}</p>
                {% endfor %}
            {% endif %}
            {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
            {% endif %}
        </div>
    {% endfor %}
    <button class="btn btn-primary btn-block" type="submit">Register</button>
</form>

<div class="mt-4 text-center">
  <small>Already have an account? <a href="{% url 'users:login' %}" class="text-primary">Login here</a></small>
</div>
{% endblock %}

templates/users/update_profile.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title>@{{ request.user.username }} | update profile</title>
{% endblock %}

{% block container %}
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-6 p-4 mt-5 mb-3" id="profile-box">
            <form action="{% url 'users:update_profile' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="media">
                    {% if profile.picture %}
                        <img src="{{ profile.picture.url }}" class="rounded-circle" height="50" width="50">
                    {% else %}
                        <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50">
                    {% endif %}
                    <div class="media-body">
                        <h5 class="ml-4">@{{user.username}} | {{user.get_full_name}}</h5>
                        <p class="ml-4">
                            <input 
                                type="file" 
                                name="picture" 
                            >
                        </p>
                    </div>
                </div>
                
                {% for error in form.picture.errors %}
                <div class="alert alert-danger">
                    <b>Picture:</b>{{error}}
                </div>
                {% endfor %}

                <hr><br>

                {# website field #}
                <div class="form-group">
                    <label>Website</label>
                    <input 
                        type="text" 
                        class="form-control {% if form.website.errors %}is-invalid{% endif %} "
                        name="website" 
                        placeholder="Website"
                        value="{% if form.errors %}{{form.website.value}}{% else %}{{ profile.website }} {% endif %}">
                        <div class="invalid-feedback">
                            {% for error in form.website.errors %}
                                {{error}}
                            {% endfor %}
                        </div>
                </div>

                {# biography field #}
                <div class="form-group">
                    <label>Biography</label>
                    <textarea 
                        class="form-control {% if form.website.errors %}is-invalid{% endif %}" 
                        name="biography">{% if form.errors %}{{form.biography.value}}{% else %}{{profile.biography}}{% endif %}
                    </textarea>
                    <div class="invalid-feedback">
                        {% for error in form.biography.errors %}
                            {{error}}
                        {% endfor %}
                    </div>
                </div>

                {# phone_number field #}
                <div class="form-group">
                    <label>Phone Number</label>
                    <input 
                        type="text"
                        class="form-control {% if form.phone_number.errors %}is-invalid{% endif %}"
                        name="phone_number"
                        placeholder="Phone Number"
                        value="{% if form.errors %}{{form.phone_number.value}}{% else %}{{ profile.phone_number }} {% endif %}">
                        <div class="invalid-feedback">
                            {% for error in form.phone_number.errors %}
                                {{error}}
                            {% endfor %}
                        </div>
                </div>

                <button type="submit" class="btn btn-primary btn-block mt-5">Update info</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}